  --------------------------------------------------------------------------------------------------
  --                                                                                              --
  -- Versión   Fecha        Nombre               Descripción del cambio                           --
  -- --------  ----------   ------------------   ------------------------------------------------ --
  -- 1.0.0     08/02/2023   Alberto Cuesta       Pet. 258 MISUMI-JAVA PISTOLA Captura Restos - 
  --                                             Restos Almacen(SISTPDV-250) (APROV-115)
  --                                             Tabla T_MIS_CAPTURA_RESTOS
  --------------------------------------------------------------------------------------------------

--TABLA T_MIS_CAPTURA_RESTOS
CREATE TABLE MISUMIADM.T_MIS_CAPTURA_RESTOS
(
    COD_CENTRO NUMBER(4) NOT NULL,
    COD_ART NUMBER(12) NOT NULL,
    FLG_MODIF_STOCK VARCHAR2(1),
    STOCK_ANTES NUMBER(10,3),
    STOCK_DESPUES NUMBER(10,3),
    FLG_MODIF_ALTO VARCHAR2(1),
    FLG_MODIF_ANCHO VARCHAR2(1),
    FLG_MODIF_FACING VARCHAR2(1),
    FACING_ANTES NUMBER(3),
    FACING_DESPUES NUMBER(3),
    CAPACIDAD_ANTES NUMBER(10,3),
    CAPACIDAD_DESPUES NUMBER(10,3),
    FLG_CAPACIDAD_INCORRECTA VARCHAR2(1) ,
    FLG_FONDO_BALDA VARCHAR2(1) ,
    FLG_MUY_ALTA_ROTACION VARCHAR2(1),
    ROTACION VARCHAR2(2),
    UNIDADES_CAJA NUMBER(7,3),
    TIPO_APROV VARCHAR2(1),
    EMPUJE VARCHAR2(1),
    COD_PLAT NUMBER(10),
    COEFICIENTE_REPOSICION NUMBER(10,3),
    FACING_EXCEDENTE_MAXIMO NUMBER(3),
    METODO_CALCULO_IMC NUMBER(2,0),
    TIPO_REFERENCIA NUMBER(1),
    FECHA_GEN DATE NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL ENABLE,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE "TS_MISUMIADM_D";

-- INDICES
CREATE UNIQUE INDEX I_T_MIS_CAPTURA_RESTOS_I1 ON T_MIS_CAPTURA_RESTOS
(COD_CENTRO, COD_ART, FECHA_GEN)
LOGGING
TABLESPACE TS_MISUMIADM_I;

--SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM T_MIS_CAPTURA_RESTOS FOR MISUMIADM.T_MIS_CAPTURA_RESTOS;

--PERMISOS
GRANT DELETE, INSERT, UPDATE, SELECT on MISUMIADM.T_MIS_CAPTURA_RESTOS to MISUMIUSR;
GRANT DELETE, INSERT, UPDATE, SELECT on MISUMIADM.T_MIS_CAPTURA_RESTOS to UNIDINUSR;
GRANT DELETE, INSERT, UPDATE, SELECT on MISUMIADM.T_MIS_CAPTURA_RESTOS to UNIDINADM;

--COMENTARIOS
COMMENT ON TABLE MISUMIADM.T_MIS_CAPTURA_RESTOS IS 'T_MIS_CAPTURA_RESTOS. Se graba un registro cada vez que el usuario de pistola pinche en una nueva referencia. Si la referencia ya existe, NO LA GRABAREMOS, sino que la mostraremos y modificaremos los flags que modifique el usuario (de momento SOLO tendrá un flag que será CAPACIDAD FACING1';

COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.COD_CENTRO IS 'Código de centro';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.COD_ART IS 'Código de referencia tienda pinchada';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FLG_MODIF_STOCK IS 'Indica que ha modificado el stock, tendrá S o nulo';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.STOCK_ANTES IS 'Stock antes del cambio';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.STOCK_DESPUES IS 'Stock después del cambio';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FLG_MODIF_ALTO IS 'Indica que se ha modificado el alto-APILAMIENTO';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FLG_MODIF_ANCHO IS 'Indica que se ha modificado el alto';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FLG_MODIF_FACING IS 'Indica que se ha modificado el facing';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FACING_ANTES IS 'Facing antes del cambio';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FACING_DESPUES IS 'Facing después del cambio';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.CAPACIDAD_ANTES IS 'Capacidad antes';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.CAPACIDAD_DESPUES IS 'Capacidad despues';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FLG_CAPACIDAD_INCORRECTA IS 'Indicador de capacidad incorrecta a facing de 1, MARCADO POR EL USUARIO';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FLG_FONDO_BALDA IS 'Fondo balda incorrecto. MARCADO POR EL USUARIO. FASE 2';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FLG_MUY_ALTA_ROTACION IS 'FASE 3. DE MOMENTO VACIO';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.ROTACION IS 'Rotación. Se graba la rotación la primera vez que se entra';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.UNIDADES_CAJA IS 'Unidades Caja';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.TIPO_APROV IS 'Tipo Aprovisionamiento';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.EMPUJE IS 'Marca de si el último registro enviado ha sido un empuje. SE guarda la primera vez que se insertan los datos';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.COD_PLAT IS 'Plataforma. Se guarda la primera';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.COEFICIENTE_REPOSICION IS 'Coeficiente Reposición. . FASE 3. DE MOMENTO VACIO';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FACING_EXCEDENTE_MAXIMO IS 'De momento irá vacio. FASE 3. DE MOMENTO VACIO';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.METODO_CALCULO_IMC IS '1-PLANOGRAMA 2-SFM 3-FAC-CAP 4-CAP-FAC 5-FAC no ali';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.TIPO_REFERENCIA IS 'Indicador de tipo de referencia: 1-expositor 2.- normal 3.- ffpp';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.FECHA_GEN IS 'Será la fecha de generación sin horas';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.CREATION_DATE IS 'Fecha y hora de creación';
COMMENT ON COLUMN MISUMIADM.T_MIS_CAPTURA_RESTOS.LAST_UPDATE_DATE IS 'Fecha y hora de la última modificación';