-- VISTA DE AGRUPACIONES COMERCIALES
create or replace view
V_AGRU_COMER_REF AS
SELECT A.NIVEL, A.GRUPO1, A.GRUPO2, A.GRUPO3, A.GRUPO4, A.GRUPO5, A.DESCRIPCION
FROM AGRU_COMER_REF A
WHERE A.FECHA_GEN =
   (SELECT MAX(B.FECHA_GEN)
    FROM AGRU_COMER_REF B
    WHERE B.NIVEL  = A.NIVEL
      AND B.GRUPO1 = A.GRUPO1
      AND B.GRUPO2 = A.GRUPO2
      AND B.GRUPO3 = A.GRUPO3
      AND B.GRUPO4 = A.GRUPO4
      AND B.GRUPO5 = A.GRUPO5
      AND B.FLG_ENVIADO_PBL = 'S'
);


-- DATOS_DIARIOS_ART
create or replace view
V_DATOS_DIARIO_ART
AS
SELECT A.COD_ART, A.DESCRIP_ART, A.GRUPO1, A.GRUPO2, A.GRUPO3, A.GRUPO4, A.GRUPO5, 
       A.CODIFI_COMER_SUP, A.CODIFI_COMER_HIP
FROM DATOS_DIARIO_ART A
WHERE A.FECHA_GEN = 
     (SELECT MAX(B.FECHA_GEN)
      FROM DATOS_DIARIO_ART B
      WHERE B.COD_ART = A.COD_ART
        AND B.FLG_ENVIADO_PBL = 'S'
      )
;
    
-- VISTA DE CENTROS
create or replace view
V_CENTROS_PLATAFORMAS
AS
    SELECT A.COD_CENTRO, A.DESCRIP_CENTRO, A.NEGOCIO
    FROM CENTROS_PLATAFORMAS A
    WHERE  A.FECHA_GEN = 
        (SELECT MAX(B.FECHA_GEN)
         FROM CENTROS_PLATAFORMAS B
         WHERE B.COD_CENTRO = A.COD_CENTRO
           AND B.FLG_ENVIADO_PBL = 'S'
           );
-- VISTA SURTIDO TIENDA
create or replace view
V_SURTIDO_TIENDA
AS
   SELECT A.COD_CENTRO, A.COD_ART, A.UNI_CAJA_SERV, A.TIPO_APROV, 
          A.MARCA_MAESTRO_CENTRO, A.CATALOGO, A.PEDIR, NULL TP_GAMA
          -- ,A.TP_GAMA
   FROM SURTIDO_TIENDA A
   WHERE A.FECHA_GEN = 
        (SELECT MAX(B.FECHA_GEN)
         FROM SURTIDO_TIENDA B
         WHERE B.COD_CENTRO = A.COD_CENTRO
           AND B.COD_ART    = A.COD_ART
           AND B.FLG_ENVIADO_PBL = 'S'
           )
      AND A.COD_CENTRO=5;
-- VISTA OFERTAS
create or replace view
V_OFERTA
AS
   SELECT A.COD_CENTRO, A.COD_ART, A.ANO_OFERTA, A.NUM_OFERTA, A.TIPO_OFERTA, 
          A.FECHA_INI, A.FECHA_FIN
          --,D.DOFTIP
   FROM  --T_SUP_OFTIP@KOSMOSCS.WORLD D, 
         OFERTA A
   WHERE A.FECHA_GEN = 
        (SELECT MAX(B.FECHA_GEN)
         FROM OFERTA B
         WHERE B.COD_CENTRO = A.COD_CENTRO
           AND B.COD_ART    = A.COD_ART
           AND B.FLG_ENVIADO_PBL = 'S'
           AND B.NOMBRE_FICHERO LIKE '%' --'I_OFEPV%'
           )
     AND A.TIPO_MENSAJE = 'A'
    -- AND A.COD_CENTRO = 5
     AND A.ANO_OFERTA = 9999 -- OJO ESTO DEBE CAMBIAR CON LA NUEVA PETICIÓN
     --AND B.TIPO_OFERTA = D.COFTIP
     ;
     
-- VISTA PLANOGRAMAS
create or replace view
V_PLANOGRAMA
AS
   SELECT A.COD_CENTRO, A.COD_ART, A.CAPACIDAD_MAX, A.STOCK_MIN_COMER
   FROM  PLANOGRAMA A
   WHERE A.FECHA_GEN = 
        (SELECT MAX(B.FECHA_GEN)
         FROM PLANOGRAMA B
         WHERE B.COD_CENTRO = A.COD_CENTRO
           AND B.COD_ART    = A.COD_ART
           AND B.FLG_ENVIADO_PBL = 'S'
           )
     ;
CREATE OR REPLACE VIEW
V_RELACION_ARTICULO
AS
   SELECT A.COD_CENTRO, A.COD_ART, A.COD_ART_RELA, D.DESCRIP_ART
   FROM  V_DATOS_DIARIO_ART D,  
         RELACION_ARTICULO A
   WHERE A.TIPO_RELA = 2
     AND A.FECHA_GEN = 
        (SELECT MAX(B.FECHA_GEN)
         FROM RELACION_ARTICULO B
         WHERE B.COD_CENTRO = A.COD_CENTRO
           AND B.COD_ART    = A.COD_ART
           AND B.FLG_ENVIADO_PBL = 'S'
           AND B.TIPO_RELA = A.TIPO_RELA
           AND B.COD_ART_RELA = A.COD_ART_RELA
           )
      AND A.COD_ART = D.COD_ART
     ;