CREATE OR REPLACE TRIGGER MISUMIADM.D_T_MIS_DETALLADO_VEGALSA_M
AFTER INSERT OR UPDATE OF CANTIDAD -- MISUMI-460 IGA -- , CANTIDAD_PROPUESTA 
ON MISUMIADM.T_MIS_DETALLADO_VEGALSA_MODIF
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE

BEGIN   
  --Si se intenta modificar una Cantidad y el dia de pedido es hoy y la hora limite es igual o superior a la hora actual no deje y de un error HA SUPERA LA HORA LIMITE.
  IF  TRUNC(:NEW.FECHA_PEDIDO)=TRUNC(SYSDATE)
  AND :NEW.HORA_LIMITE <  to_char(sysdate, 'HH24MI')
  THEN
	RAISE_APPLICATION_ERROR(-20001,'HA SUPERADO LA HORA LIMITE.');    
  END IF;
END;
/