CREATE OR REPLACE TRIGGER MISUMIADM.D_T_MIS_DEVOLUCIONES_BULTO
BEFORE INSERT ON MISUMIADM.T_MIS_DEVOLUCIONES_BULTO
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW

BEGIN
  :new.fecha_gen := TRUNC(:new.fecha_gen);
END;
/